### PR TITLE
Issues/46 could not find declaration

### PR DESCRIPTION
**Pull request by rakotomandimby**
Hello @y-takey ,

I managed to solve the issue with Rect and I bring back some contribution.

Hoping for a merge.

### CODE REVIEW

**Comment by rakotomandimby** [comment]
While still facing the problem, I asked on stackoverflow: https://stackoverflow.com/questions/69048899/could-not-find-a-declaration-file-for-module-chartjs-plugin-stacked100/69104344#69104344

**Comment by LeeLenaleee** [comment]
Instead of making some documentation and and a react sample about how you solved it by creating a global typing file, it would be much better to just provide typing out of the box.

**Review by y-takey — APPROVED** [review]
LGTM 👍

**Comment by y-takey** [comment]
@LeeLenaleee Thanks for your advice. I'll try to generate the typing file.

**Comment by rakotomandimby** [comment]
@LeeLenaleee  , I dont know how to do what you suggest. I contribute with what I know. May be should you point me to the documentation on how to do that. Thank you.

**Comment by LeeLenaleee** [comment]
You can take https://github.com/chartjs/Chart.js/pull/7668 as a basis to see how its done in the main repo, main thing that is wrong about that pr is how is linked to the types from the package.json, instead of taking it out of the dist from the build its referencing it directly now like so: `"types": "types/index.esm.d.ts",`

**Pull request merged**
